moviesDB/config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'pages#home', as: 'home'
  post '/', to: 'pages#search'

  get  '/movies/:id/genres/', to: 'genres#index', as: 'genres'
  post '/movies/:id/genres/', to: 'genres#create'
  delete '/genres/:id', to: 'genres#delete', as: 'genre'

  get  '/movies/:id/actors/', to: 'actors#index', as: 'actors'
  post '/movies/:id/actors/', to: 'actors#create'
  delete '/actors/:id', to: 'actors#delete', as: 'actor'

  get  '/movies/:id/ratings/', to: 'ratings#index', as: 'ratings'
  post '/movies/:id/ratings/', to: 'ratings#create'
  delete '/ratings/:id', to: 'ratings#delete', as: 'rating'

  resources :movies

  post '/api/1/movies', to:'actions#create_movie'
  delete '/api/1/movies/:id', to:'actions#delete_movie'

end

moviesDB/app/models/actor.rb
class Actor < ApplicationRecord
    belongs_to :movie
end

moviesDB/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

    self.abstract_class = true

end

moviesDB/app/models/genre.rb
class Genre < ApplicationRecord
    belongs_to :movie
end

moviesDB/app/models/movie.rb
class Movie < ApplicationRecord
    has_many :genres, dependent: :destroy
    has_many :ratings, dependent: :destroy
    has_many :actors, dependent: :destroy
end

moviesDB/app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :movie
end

moviesDB/app/controllers/actions_controller.rb

class ActionsController < ApplicationController
    
    skip_before_action :verify_authenticity_token
    
    def delete_movie
        begin
            @movie = Movie.find(params[:id])
            @movie.destroy
            render :json => "movie deleted"
        rescue ActiveRecord::RecordNotFound
            render :json => "movie not found"
        end
    end

    def create_movie
        @movie = Movie.new()

        @movie.title = params[:title]
        @movie.year = params[:year]
        @movie.poster = params[:poster]
        @movie.contentRating = params[:contentRating]
        @movie.duration = params[:duration]
        @movie.releaseDate = params[:releaseDate]
        @movie.originalTitle = params[:originalTitle]
        @movie.storyline = params[:storyline]
        @movie.imdbRating = params[:imdbRating]
        @movie.posterURL = params[:posterurl]
        @movie.averageRating =params[:averageRating]

        @movie.save
        render :json => @movie.id
    end
end

moviesDB/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
        @movie = Movie.find(params[:id])
    end

    def delete
        @actor = Actor.find(params[:id])
        @movie_id = @actor.movie_id
        @actor.destroy
        redirect_to actors_path(@movie_id)
    end

    def create
        @movie = Movie.find(params[:id])
        @movie.actors.create(name: params.require("name")) if params[:name].present?
        redirect_to actors_path(@movie.id)
    end
end

moviesDB/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

moviesDB/app/controllers/genres_controller.rb
class GenresController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
        @movie = Movie.find(params[:id])
    end

    def delete
        @genre = Genre.find(params[:id])
        @movie_id = @genre.movie_id
        @genre.destroy
        redirect_to genres_path(@movie_id)
    end

    def create
        @movie = Movie.find(params[:id])
        @movie.genres.create(name: params.require("name")) if params[:name].present?
        redirect_to genres_path(@movie.id)
    end
end

moviesDB/app/controllers/movies_controller.rb

class MoviesController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
        @movies = Movie.all
    end

    def show
        @movie = Movie.find(params[:id])
    end

    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        @movie = Movie.find(params[:id])
        
        @movie.update(movie_params)
        redirect_to movie_path(@movie.id)
    end

    def new
        @movie = Movie.new()
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
        redirect_to movies_path
    end

    def create
        @movie = Movie.create(movie_params)
        redirect_to movie_path(@movie.id)
    end

    private

    def movie_params
        params.require(:movie).permit(
            :title,
            :year,
            :poster,
            :contentRating,
            :duration,
            :releaseDate,
            :averageRating,
            :originalTitle,
            :storyline,
            :imdbRating,
            :posterURL)
    end
end

moviesDB/app/controllers/pages_controller.rb
require "rubygems/text"

class PagesController < ApplicationController
    
    def home
    end

    def search
        @title = params[:title]

        if (@title == nil)
            @title = ''
        end

        @title = @title.downcase
        
        lev_dist = Class.new.extend(Gem::Text).method(:levenshtein_distance)

        @list = Movie.all.sort_by{|m| m.title != nil ? lev_dist.call(m.title.downcase, @title): lev_dist.call('', @title)}
    end
end

moviesDB/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
        @movie = Movie.find(params[:id])
    end

    def delete
        @rating = Rating.find(params[:id])
        @movie_id = @rating.movie_id
        @rating.destroy
        redirect_to ratings_path(@movie_id)
    end

    def create
        @movie = Movie.find(params[:id])
        @movie.ratings.create(value: params.require("value")) if params[:value].present?
        redirect_to ratings_path(@movie.id)
    end
end

moviesDB/app/helpers/application_helper.rb
module ApplicationHelper
end

moviesDB/app/views/actors/index.html.erb
<h1>
    actors of <a href="<%=movie_path(@movie.id)%>"><%= @movie.title%></a>
</h1>
<div>
    <%@movie.actors.each do |a|%>
        <p>
            <%=a.name%> | 
            <a href="<%= actor_path(a.id)%>" class="delete" data-confirm="Delete <%=a.name %> from <%= @movie.title %> ?" data-method="DELETE">delete</a>
        </p>
    <% end %>

    <%= form_tag(url: actors_path(@movie.id), method: "post") do %>
        <%= label_tag("", "name :") %>
        <%= text_field_tag(:name) %>
        <%= submit_tag("add") %>
    <% end %>
</div>

moviesDB/app/views/genres/index.html.erb
<h1>
    genres of <a href="<%=movie_path(@movie.id)%>"><%= @movie.title%></a>
</h1>
<div>
    <%@movie.genres.each do |g|%>
        <p>
            <%=g.name%> | 
            <a href="<%= genre_path(g.id)%>" class="delete" data-confirm="Delete <%=g.name %> from <%= @movie.title %> ?" data-method="DELETE">delete</a>
        </p>
    <% end %>

    <%= form_tag(url: genres_path(@movie.id), method: "post") do %>
        <%= label_tag("", "name :") %>
        <%= text_field_tag(:name) %>
        <%= submit_tag("add") %>
    <% end %>
</div>

moviesDB/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoviesDB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="topNavigationBar">
    <a href=<%= home_path%>>Home</a>
    <a href=<%= movies_path%>>index</a>
</div>
<div class="content">
    <%= yield %>
</div>


</body>
</html>

moviesDB/app/views/movies/edit.html.erb

<%= form_for @movie do |f|%>
    <div class="form_field">
        <label>title :</label>
        <%= f.text_field :title%>
    </div>
    <div class="form_field">
        <label>year :</label>
        <%= f.number_field :year%>
    </div>
    <div class="form_field">
        <label>poster :</label>
        <%= f.text_field :poster, size: "100"%>
    </div>
    <div class="form_field">
        <label>content's rating :</label>
        <%= f.number_field :contentRating, step: :any%>
    </div>
    <div class="form_field">
        <label>duration :</label>
        <%= f.text_field :duration%>
    </div>
    <div class="form_field">
        <label>release date :</label>
        <%= f.date_select :releaseDate, 
            :order => [:day, :month, :year], 
            :start_year => 1920, 
            :end_year => Date.today.year, 
            :html=>{:class => "input-mini"} 
        %>
    </div>
    <div class="form_field">
        <label>rating's average :</label>
        <%= f.number_field :averageRating, step: :any%>
    </div>
    <div class="form_field">
        <label>original title :</label>
        <%= f.text_field :originalTitle%>
    </div>
    <div class="form_field">
        <p><label>storyline :</label></p>
        
        <%= f.text_area :storyline, cols: "100", rows: "10"%>
    </div>
    <div class="form_field">
        <label>imdb rating :</label>
        <%= f.number_field :imdbRating, step: :any%>
    </div>
    <div class="form_field">
        <label>poster's url :</label>
        <%= f.url_field :posterURL, size: "100"%>
    </div>

    <div class="form_field">
        <button type="submit">modify</label>
    </div>
<%end%>

moviesDB/app/views/movies/index.html.erb

<h1> movies list </h1>
<p>
    <a href="<%= new_movie_path%>">add new movie</a>
</p>
<div style="border-left: solid; padding: 10px;">
    <% @movies.each do |m|%>
        <div>
            <a href="<%= movie_path(m.id)%>">
                <%= m.id %>. <%= m.title %>
            </p>    
        <div>
    <% end %>
</div>

moviesDB/app/views/movies/new.html.erb

<%= form_for @movie do |f|%>
    <div class="form_field">
        <label>title :</label>
        <%= f.text_field :title%>
    </div>
    <div class="form_field">
        <label>year :</label>
        <%= f.number_field :year%>
    </div>
    <div class="form_field">
        <label>poster :</label>
        <%= f.text_field :poster, size: "100"%>
    </div>
    <div class="form_field">
        <label>content's rating :</label>
        <%= f.number_field :contentRating, step: :any%>
    </div>
    <div class="form_field">
        <label>duration :</label>
        <%= f.text_field :duration%>
    </div>
    <div class="form_field">
        <label>release date :</label>
        <%= f.date_select :releaseDate, 
            :order => [:day, :month, :year], 
            :start_year => 1920, 
            :end_year => Date.today.year, 
            :html=>{:class => "input-mini"} 
        %>
    </div>
    <div class="form_field">
        <label>rating's average :</label>
        <%= f.number_field :averageRating, step: :any%>
    </div>
    <div class="form_field">
        <label>original title :</label>
        <%= f.text_field :originalTitle%>
    </div>
    <div class="form_field">
        <p><label>storyline :</label></p>
        
        <%= f.text_area :storyline, cols: "100", rows: "10"%>
    </div>
    <div class="form_field">
        <label>imdb rating :</label>
        <%= f.number_field :imdbRating, step: :any%>
    </div>
    <div class="form_field">
        <label>poster's url :</label>
        <%= f.url_field :posterURL, size: "100"%>
    </div>

    <div class="form_field">
        <button type="submit">create</label>
    </div>
<%end%>

moviesDB/app/views/movies/show.html.erb
<h1>
    <%= @movie.title%>
</h1>

<p>
    id : <%= @movie.id%>
</p>
<p>
    year : <%= @movie.year%>
</p>
<p>
    genres : <%= @movie.genres.map{|g| g.name}.join(", ") %>
    | <a href="<%= genres_path(@movie.id)%>">edit</a>
</p>
<p>
    ratings : <%= @movie.ratings.map{|g| g.value}.join(", ") %>
    | <a href="<%= ratings_path(@movie.id)%>">edit</a>
</p>
<p>
    content's rating : <%= @movie.contentRating%>
</p>
<p>
    duration : <%= @movie.duration%>
</p>
<p>
    release's date : <%= @movie.releaseDate%>
</p>
<p>
    rating's average : <%= @movie.averageRating%>
</p>

<%if (@movie.originalTitle != nil and @movie.originalTitle.length > 0)%>
    <p>
        original title : <%= @movie.originalTitle%>
    </p>
<%end%>

<p>
    storyline : <%= @movie.storyline%>
</p>
<p>
    actors : <%= @movie.actors.map{|g| g.name}.join(", ") %>
    | <a href="<%= actors_path(@movie.id)%>">edit</a>
</p>
<p>
    imdb rating : <%= @movie.imdbRating%>
</p>
<p>
    <a href="<%= edit_movie_path(@movie.id)%>">edit</a>
    <a href="<%= movie_path(@movie.id)%>" class="delete" data-confirm="Delete <%=@movie.title %> ?" data-method="DELETE">delete</a>
</p>

moviesDB/app/views/pages/home.html.erb

<%= form_tag(url: home_path, method: "post") do %>
    <%= label_tag("", "title :") %>
    <%= text_field_tag(:title) %>
    <%= submit_tag("search") %>
<% end %>

moviesDB/app/views/pages/search.html.erb

<h2> research result for '<%= @title %>' | <a href="<%=home_path%>">back</a></h1>

<div style="border-left: solid; padding: 10px;">
    <% @list.each do |m|%>
        <div>
            <a href="<%= movie_path(m.id)%>">
                <%= m.id %>. <%= m.title %>
            </p>    
        <div>
    <% end %>
</div>

moviesDB/app/views/ratings/index.html.erb
<h1>
    ratings of <a href="<%=movie_path(@movie.id)%>"><%= @movie.title%></a>
</h1>
<div>
    <%@movie.ratings.each do |r|%>
        <p>
            <%=r.value%> | 
            <a href="<%= rating_path(r.id)%>" class="delete" data-confirm="Delete <%=r.value %> from <%= @movie.title %> ?" data-method="DELETE">delete</a>
        </p>
    <% end %>

    <%= form_tag(url: ratings_path(@movie.id), method: "post") do %>
        <%= label_tag("", "value :") %>
        <%= text_field_tag(:value) %>
        <%= submit_tag("add") %>
    <% end %>
</div>